# .github/workflows/selfhosted-runner.yml
name: Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Show system info
        run: |
          echo "Runner Hostname: $(hostname)"
          echo "OS Info:"
          uname -a
      - name: Trigger GitLab pipeline
        run: |
          curl -X POST "https://gitlab.dev.net/api/v4/projects/35/trigger/pipeline" \
            --form token=${{ secrets.GITLAB_TRIGGER_TOKEN }} \
            --form ref=mirror-ci
